-- Migration: Alert System Tables
-- This migration creates the database schema for the alert system:
-- - market_data: stores external data (mortgage rates, HPI data)
-- - alert_rules: defines alert rule configurations
-- - generated_alerts: stores generated alerts for properties
-- - user_alert_state: tracks user interactions with alerts

-- Market Data Table
-- Stores time-series data from external sources (FRED, FHFA)
CREATE TABLE market_data (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  data_type TEXT NOT NULL CHECK (data_type IN ('mortgage_rate', 'hpi')),
  region_type TEXT NOT NULL CHECK (region_type IN ('national', 'state', 'metro', 'zip3')),
  region_code TEXT NOT NULL,
  effective_date DATE NOT NULL,
  value NUMERIC(10,4) NOT NULL,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(data_type, region_type, region_code, effective_date)
);

CREATE INDEX idx_market_data_lookup ON market_data(data_type, region_type, region_code, effective_date DESC);
CREATE INDEX idx_market_data_date ON market_data(effective_date DESC);

COMMENT ON TABLE market_data IS 'Stores external market data from FRED and FHFA for alert generation';
COMMENT ON COLUMN market_data.data_type IS 'Type of data: mortgage_rate (FRED) or hpi (FHFA House Price Index)';
COMMENT ON COLUMN market_data.region_type IS 'Geographic scope: national, state, metro, or zip3';
COMMENT ON COLUMN market_data.region_code IS 'Region identifier (state abbrev, metro name, or zip prefix)';
COMMENT ON COLUMN market_data.value IS 'The data value (percentage for rates/HPI, or absolute values)';
COMMENT ON COLUMN market_data.metadata IS 'Additional context (source, series ID, etc.)';

-- Alert Rules Table
-- Defines the configuration for different alert types
CREATE TABLE alert_rules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rule_type TEXT NOT NULL,
  enabled BOOLEAN DEFAULT true,
  parameters JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_alert_rules_enabled ON alert_rules(enabled) WHERE enabled = true;
CREATE INDEX idx_alert_rules_type ON alert_rules(rule_type);

COMMENT ON TABLE alert_rules IS 'Configuration for different alert rule types';
COMMENT ON COLUMN alert_rules.rule_type IS 'Alert type (refinance_opportunity, market_appreciation, lease_expiration, etc.)';
COMMENT ON COLUMN alert_rules.enabled IS 'Whether this rule should be evaluated';
COMMENT ON COLUMN alert_rules.parameters IS 'Rule-specific configuration (thresholds, frequencies, etc.)';

-- Generated Alerts Table
-- Stores alerts generated by the alert engine
CREATE TABLE generated_alerts (
  id TEXT PRIMARY KEY,
  rule_id UUID REFERENCES alert_rules(id) ON DELETE CASCADE,
  property_id UUID REFERENCES properties(id) ON DELETE CASCADE,
  severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  estimated_value NUMERIC(10,2),
  action_deadline DATE,
  triggered_at TIMESTAMPTZ NOT NULL,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_generated_alerts_property ON generated_alerts(property_id);
CREATE INDEX idx_generated_alerts_rule ON generated_alerts(rule_id);
CREATE INDEX idx_generated_alerts_severity ON generated_alerts(severity);
CREATE INDEX idx_generated_alerts_triggered ON generated_alerts(triggered_at DESC);
CREATE INDEX idx_generated_alerts_deadline ON generated_alerts(action_deadline) WHERE action_deadline IS NOT NULL;

COMMENT ON TABLE generated_alerts IS 'Alerts generated by the alert engine for user properties';
COMMENT ON COLUMN generated_alerts.id IS 'Hash-based ID combining rule + property + date for idempotency';
COMMENT ON COLUMN generated_alerts.severity IS 'Alert priority level: low, medium, high, or critical';
COMMENT ON COLUMN generated_alerts.estimated_value IS 'Estimated financial impact (savings, gains, losses)';
COMMENT ON COLUMN generated_alerts.action_deadline IS 'Date by which user should take action';
COMMENT ON COLUMN generated_alerts.metadata IS 'Alert-specific data (rates, comparisons, links, etc.)';

-- User Alert State Table
-- Tracks user interactions with alerts (read, dismissed)
CREATE TABLE user_alert_state (
  alert_id TEXT PRIMARY KEY REFERENCES generated_alerts(id) ON DELETE CASCADE,
  is_read BOOLEAN DEFAULT false,
  is_dismissed BOOLEAN DEFAULT false,
  dismissed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_user_alert_state_unread ON user_alert_state(is_read) WHERE is_read = false;
CREATE INDEX idx_user_alert_state_dismissed ON user_alert_state(is_dismissed, dismissed_at);

COMMENT ON TABLE user_alert_state IS 'Tracks user interactions with generated alerts';
COMMENT ON COLUMN user_alert_state.is_read IS 'Whether the user has viewed this alert';
COMMENT ON COLUMN user_alert_state.is_dismissed IS 'Whether the user has dismissed this alert';
COMMENT ON COLUMN user_alert_state.dismissed_at IS 'Timestamp when alert was dismissed';

-- Add updated_at trigger for market_data
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_market_data_updated_at BEFORE UPDATE ON market_data
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_alert_rules_updated_at BEFORE UPDATE ON alert_rules
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_alert_state_updated_at BEFORE UPDATE ON user_alert_state
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
